[project]
name = "speech-segmentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "kittentts",
    "numpy>=2.4.6",
    "onnx>=1.21.0",
    "onnxruntime>=1.26.0",
    "onnxscript>=0.7.0",
    "scikit-learn>=1.8.0",
    "soundfile>=0.14.0",
    "speechbrain>=1.1.0",
    "transformers>=5.9.0",
]

[tool.uv.sources]
kittentts = { url = "https://github.com/KittenML/KittenTTS/releases/download/0.8.1/kittentts-0.8.1-py3-none-any.whl" }

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = ["I"]

[dependency-groups]
dev = [
    "deno>=2.9.0",
    "ruff>=0.15.20",
    "ty>=0.0.55",
]
